[tool.poetry]
name = "easyapply"
version = "0.1.0"
description = "CVs generate from YAML."
authors = ["Fabian Köhler <me@fkoehler.org>"]
readme = "README.md"

[tool.poetry.scripts]
easyapply = "easyapply.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
jinja2 = "^3.1.2"
pyyaml = "^6.0"
typer = { extras = ["all"], version = "^0.7.0" }


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
mypy = "^0.991"
isort = "^5.11.4"
black = "^22.12.0"
types-pyyaml = "^6.0.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
